### ISSUE TITLE
Font for homescreen tabs

### ISSUE THREAD

**Issue by richwaight** [4water/weare4water.org#10] opened 2014-05-27 15:31 UTC
I'm not sure if this is the kind of comment you were looking for...
But the font for the tabs on the homepage is not crystal clear. I know its supposed to look like hand writing and whilst I'm not a designer, text (and buttons) should be instantly readable/recognisable. I'm not suggesting Ariel, but perhaps not faux handwriting.

**Comment by Salsa4water-Lyon** [comment] 2014-05-28 22:19
I do agree with richwaight : the handwriting font is not quite clear. Besides, it's not the same as used in e.g. Glasgow videos (they use Segoe Print) and it takes pretty much space to write small things.

**Comment by iporter** [comment] 2014-06-02 11:18
Closing as duplicate of general font issue documented elsewhere.

**Closed as completed by iporter** 2014-06-02 11:18 UTC
Labels: duplicate
