### ISSUE TITLE
FAQ and text in general

### ISSUE THREAD

**Issue by awmohr** [4water/weare4water.org#26] opened 2014-05-30 20:49 UTC
Again, I like the technical idea of how the site works with resized browsers. But make it so that the text has at least a small space between the edge of the window. Otherwise I just don't want to read anything. 

![capture decran 2014-05-30 a 22 47 31](https://cloud.githubusercontent.com/assets/7750063/3135991/dc036a52-e83b-11e3-8aa4-f7c562f269e8.png)

**Comment by iporter** [comment] 2014-06-02 11:22
Closed as duplicate of other issue documenting lack of margins on mobile devices.

**Closed as completed by iporter** 2014-06-02 11:22 UTC
Labels: duplicate
