### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by awmohr** [4water/weare4water.org#25] opened 2014-05-30 20:46 UTC
Aside from being basically empty (not a problem for here). This is a screenshot of my resized browser on this page. I can't even begin to understand whats going on here. 

More simply the search bar has the whole damn "Search" button cut off so it's just a little magnifying glass that seems to have no purpose.

![capture decran 2014-05-30 a 22 44 07](https://cloud.githubusercontent.com/assets/7750063/3135975/686d0fbc-e83b-11e3-8e5e-144da7fb4c05.png)

**Comment by iporter** [comment] 2014-06-02 11:30
Closing as duplicate of other issues.

**Closed as completed by iporter** 2014-06-02 11:30 UTC
